<?php
/**
 * Created by PhpStorm.
 * User: Ivan
 * Date: 13.02.2019
 * Time: 15:49
 */

namespace core\base;


abstract class RestController extends Controller
{
    public function execAction(string $action)
    {
        return json_encode(parent::execAction($action)); // TODO: Change the autogenerated stub
    }

}