<?php
/**
 * Created by PhpStorm.
 * User: Ivan
 * Date: 13.02.2019
 * Time: 15:09
 */

namespace core\base;


class TemplateView extends View

{
    private $view;

    public function __construct($name,$template)
    {
        $this->view = new View($name);
        parent::__construct("templates/".$template);
    }

    public function render($data = [])
    {
        $this->data["content"]=$this->view->render(array_merge($data,$this->data));
        return parent::render($data); // TODO: Change the autogenerated stub
    }

}